globalProperties:
  apiTests: false
  modelTests: false  
  apiDocs: false
  modelDocs: false
additionalProperties:
  hideGenerationTimestamp: true
  packageName: itportalapi
  disallowAdditionalPropertiesIfNotPresent: false
  enumClassPrefix: true